### ISSUE TITLE
Repository naming due to Moodle naming suggestion

### ISSUE THREAD

**Issue by peta3000** [davosmith/moodle-objectives#4]
Hii and first of all, thanks a lot for this wonderful plugin.

I was wandering if you would like to consider to adjust the repository's naming to that of Moodle's suggested way of repo-naming?
e.g. moodle-block_objectives
like documented here:
https://docs.moodle.org/dev/Plugin_contribution#Repository

Cheers

peta

**Comment by davosmith** [comment]
The plugin repository predates Moodle's suggested repo-naming convention (which is why it doesn't follow it).

I am not aware of any particular reason why I should retrospectively change the name of the repository - it doesn't cause any problems that I'm aware of (the Moodle plugins directory where it should be downloaded from is unaffected).

**Comment by peta3000** [comment]
Cool!
Makes sense. :) 
Thanks for your quick reply and explanation.
Question has been answered and issue can be closed.

have a lovely day!
cheers

peta

**Comment by davosmith** [comment]
As an aside - glad the plugin's still useful. It's not one of my more prominent plugins (it was really just written for my own use when I was a classroom teacher), and I occasionally wonder if it's worth the (fairly small) effort of keeping it updated with new Moodle releases. Knowing that at least one person still uses it is enough to keep it on my maintenance  list ...
